name: Performance Tests (.NET + JMeter)

on:
  workflow_call:

env:
  TARGET_MACHINE: ${{ secrets.JMETER_MACHINE }}
  USERNAME: ${{ secrets.LOGIN_USER }}
  PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  run-tests:
    runs-on: [self-hosted, windows]

    steps:
      - name: Close pending Java processes (remote)
        shell: pwsh
        run: |
          Write-Host "Closing pending Java processes on TARGET_MACHINE: ${{ env.TARGET_MACHINE }}"
          Write-Host "Username : ${{ env.USERNAME }}"
          $secpasswd = ConvertTo-SecureString "${{ env.LOGIN_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("${{ env.USERNAME }}", $secpasswd)

          $scriptPath = "${{ env.POWERSHELL_SCRIPT_PATH }}\Jmeter\JmeterServer.ps1"

          Invoke-Command -ComputerName "${{ env.TARGET_MACHINE }}" -Credential $creds -ScriptBlock {
              . $using:scriptPath
              CloselocalProcess
          } -Authentication Negotiate -ErrorAction Continue

        continue-on-error: true
