name: Performance Tests (.NET + JMeter)

on:
  workflow_call:

env:
  TARGET_MACHINE: ${{ secrets.JMETER_MACHINE }}
  USERNAME: ${{ secrets.LOGIN_USER }}
  PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  run-tests:
    runs-on: [self-hosted, windows]

    steps:
      - name: Close pending Java processes (remote)
        shell: pwsh
        run: |
          Write-Host "Closing pending Java processes on TARGET_MACHINE: ${{ inputs.target-machine }}"
          Write-Host "Username : ${{ inputs.username }}"

          $secpasswd = ConvertTo-SecureString "${{ secrets.login-password }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("${{ inputs.username }}", $secpasswd)

          $scriptPath = "${{ inputs.powershell-script-path }}\Jmeter\JmeterServer.ps1"

          Invoke-Command -ComputerName "${{ inputs.target-machine }}" -Credential $creds -ScriptBlock {
              . $using:scriptPath
              CloselocalProcess
          } -Authentication Negotiate -ErrorAction Continue
        continue-on-error: true
