name: Close Pending Java Processes

on:
  workflow_call:
    secrets:
      jm-machine:
        required: true
      login-user:
        required: true
      login-password:
        required: true
      script-path:
        required: true

jobs:
  close-java:
    runs-on: [self-hosted, windows]
    steps:
      - name: Close Java Processes
        shell: pwsh
        run: |
          Write-Host "Running on: ${{ secrets.jm-machine }}"
          Write-Host "User: ${{ secrets.login-user }}"

          $secpasswd = ConvertTo-SecureString "${{ secrets.login-password }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("${{ secrets.login-user }}", $secpasswd)

          $scriptPath = "${{ secrets.script-path }}\\Jmeter\\JmeterServer.ps1"

          Invoke-Command -ComputerName "${{ secrets.jm-machine }}" -Credential $creds -ScriptBlock {
              . $using:scriptPath
              CloselocalProcess
          } -Authentication Negotiate -ErrorAction Continue
        continue-on-error: true
