name: Performance Tests (.NET + JMeter)

on:
  workflow_dispatch: # Manual trigger for now

env:
  TARGET_MACHINE: ${{ secrets.JMETER_MACHINE }}
  USERNAME: ${{ secrets.LOGIN_USER }}
  PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Close pending Java processes (remote)
        shell: pwsh
        run: |
          $secpasswd = ConvertTo-SecureString "${{ secrets.LOGIN_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("${{ secrets.LOGIN_USER }}", $secpasswd)

          $scriptPath = "${{ secrets.POWERSHELL_SCRIPT_PATH }}\Jmeter\JmeterServer.ps1"

          Invoke-Command -ComputerName "${{ secrets.JMETER_MACHINE }}" -Credential $creds -ScriptBlock {
              . $using:scriptPath
              CloselocalProcess
          } -Authentication Negotiate -ErrorAction Continue
        continue-on-error: true
