name: Performance Tests (.NET + JMeter)

on:
  workflow_dispatch: # Manual trigger for now

env:
  TARGET_MACHINE: ${{ secrets.JMETER_MACHINE }}
  USERNAME: ${{ secrets.LOGIN_USER }}
  PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  run-tests:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Close pending Java processes (remote)
        shell: pwsh
        run: |
          Write-Host "Closing pending Java processes on ${{ env.TARGET_MACHINE }}"
          $secpasswd = ConvertTo-SecureString "${{ secrets.LOGIN_PASSWORD }}" -AsPlainText -Force
          $creds = New-Object System.Management.Automation.PSCredential ("${{ secrets.LOGIN_USER }}", $secpasswd)

          $scriptPath = "${{ secrets.POWERSHELL_SCRIPT_PATH }}\Jmeter\JmeterServer.ps1"

          Invoke-Command -ComputerName "${{ secrets.JMETER_MACHINE }}" -Credential $creds -ScriptBlock {
              . $using:scriptPath
              CloselocalProcess
          } -Authentication Negotiate -ErrorAction Continue
        continue-on-error: true
# use actions/checkout@v4
# try to use the $TARGET_MACHINE variable not secret.Varname
# use jobs, multi-job strategies
