name: Performance Tests (.NET + JMeter)

on:
  workflow_dispatch: # Manual trigger for now

env:
  TARGET_MACHINE: ${{ secrets.JMETER_MACHINE }}
  USERNAME: ${{ secrets.LOGIN_USER }}
  PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

jobs:
  close-java-processes:
    uses: ./.github/workflows/ClosePendingJava_Reusable.yml@main

    # runs-on: [self-hosted, windows]

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Close pending Java processes (remote)
    # shell: pwsh
    # run: |
    #   Write-Host "Closing pending Java processes on TARGET_MACHINE: ${{ env.TARGET_MACHINE }}"
    #   Write-Host "Username : ${{ env.USERNAME }}"
    #   $secpasswd = ConvertTo-SecureString "${{ env.LOGIN_PASSWORD }}" -AsPlainText -Force
    #   $creds = New-Object System.Management.Automation.PSCredential ("${{ env.USERNAME }}", $secpasswd)

    #   $scriptPath = "${{ env.POWERSHELL_SCRIPT_PATH }}\Jmeter\JmeterServer.ps1"

    #   Invoke-Command -ComputerName "${{ env.TARGET_MACHINE }}" -Credential $creds -ScriptBlock {
    #       . $using:scriptPath
    #       CloselocalProcess
    #   } -Authentication Negotiate -ErrorAction Continue
    # continue-on-error: true
  # use actions/checkout@v4
  # try to use the $TARGET_MACHINE variable not secret.Varname
  # use jobs, multi-job strategies
  run-next:
    runs-on: [self-hosted, windows]

    steps:
      - name: Logging Information
        run: |
          Write-Host "Working fine"
